swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /v1.0

paths:
  /users:
    get:
      description: Get all users
      operationId: app.methods.methods.get_all_users

      responses:
        '200':
          description: 'Fetch a list of users'
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      description: Create new user
      operationId: app.methods.methods.create_user

      parameters:
      - in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/PetRegistration'
      responses:
        '201':
          description: 'Register a new user'

  '/users/{uuid}':
    get:
      description: Get user by id
      operationId: app.methods.methods.get_user_by_id

      parameters:
        - in: path
          name: uuid
          required: true
          type: string
      responses:
        '200':
          description: 'Fetch a user by ID'
          schema:
            $ref: '#/definitions/User'

definitions:
  PetRegistration:
    type: object
    properties:
      name:
        type: string
  User:
    type: object
    properties:
      uuid:
        type: string
      name:
        type: string
